function getList() {
	var availableTags = [
	  "ActionScript",
	  "AppleScript",
	  "Asp",
	  "BASIC",
	  "C",
	  "C++",
	  "Clojure",
	  "COBOL",
	  "ColdFusion",
	  "Erlang",
	  "Fortran",
	  "Groovy",
	  "Haskell",
	  "Java",
	  "JavaScript",
	  "Lisp",
	  "Perl",
	  "PHP",
	  "Python",
	  "Ruby",
	  "Scala",
	  "Scheme",
	  "Accounting",
	  "Admin Work",
	  "Cashier Work",
	  "Cleaner",
	  "Data Entry",
	  "Delivery",
	  "Driving",
	  "Flyer Distribution",
	  "Food and Beverage",
	  "Graphic Design",
	  "Marketing",
	  "Nursing",
	  "Promoting",
	  "Reception",
	  "Survey",
	  "Telemarketing",
	  "Bartending",
	  "Cook",
	  "Editing",
	  "Event Planning",
	  "Fundraising",
	  "Translating",
	  "Photographing",
	  "Plumbing",
	  "Retailing",
	  "Social Work",
	  "Foods and Services"
	];
	return availableTags;
}


